/**
 * dsh-whale-sway — host half.
 *
 * The animation itself is client-side. This half exists for two reasons.
 *
 * ## 1. The bundle layer needs a row
 *
 * A package's `dsh.bundle` patch must insert a Loader entry for the package to
 * be instantiated, and the manifest's `dsh.client` declaration is only
 * discovered for a package the active profile has enabled. So this module is
 * the row: it owns no Host service, registers no tool, and holds no state.
 *
 * ## 2. The row's Config schema is what makes the plugin configurable
 *
 * DSH's settings domain projects a form out of a Loader entry's Config schema
 * (`@deepseek-ai/dsh-settings`: `describe()` → `volatileForm(schema)` → the
 * entry's editable fields) and persists every accepted edit into the profile
 * patch. The browser half then reads the same document through
 * `ctx.configForms.get('dsh-whale-sway')` and paints with it. So the schema
 * declared here *is* the configuration interface: each field is a parameter the
 * settings page exposes, its `.default()` is what the plugin runs with before
 * any override exists, and its bounds are what the Host validates a write
 * against.
 *
 * Every field is `.volatile()`: a volatile field is one the Loader can apply to
 * the running instance without a remount, and it is also the only kind
 * `volatileForm()` selects, so a non-volatile field would render nowhere.
 *
 * ## Why the schema package is resolved instead of imported
 *
 * A plugin installed with `link:` (or run from a checkout) resolves bare
 * specifiers from its own real path, which is outside any `node_modules` chain
 * that carries `@deepseek-ai/schemastery`; a static `import` would therefore
 * throw before this module ever exports anything, and the whole plugin would
 * fail to load rather than merely lose its settings page. The schema factory is
 * resolved at module load instead — from the running profile first, which is
 * where DSH keeps every package the composition can see — and the module
 * degrades to "no Config, no settings page" when resolution fails, leaving the
 * animation intact.
 *
 * The field table is not authored here: `tools/sync-settings.mjs` splices the
 * generated block below from `tools/settings.mjs`, the same table the browser
 * half and its tests read.
 */

import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Cordis plugin name — must match the package name and the bundle patch row. */
export const name = 'dsh-whale-sway';

/** No Host dependencies: this plugin touches no Host service. */
export const inject = [];

/** The schema package whose factory builds the Config schema. */
const SCHEMA_PACKAGE = '@deepseek-ai/schemastery';

/* dsh-whale-sway:settings:begin */
// Generated by `node tools/sync-settings.mjs` from tools/settings.mjs.
// Do not edit by hand: this is the same parameter table the other half
// generates from, and `node tools/sync-settings.mjs --check` fails on drift.
var SETTINGS_FIELDS = [
  {
    "id": "mode",
    "group": "sway",
    "control": "segmented",
    "type": "enum",
    "values": [
      "sway",
      "sway-gentle",
      "sway-vivid"
    ],
    "default": "sway",
    "options": [
      {
        "value": "sway",
        "label": {
          "zh": "原生",
          "en": "As drawn"
        }
      },
      {
        "value": "sway-gentle",
        "label": {
          "zh": "轻摆",
          "en": "Gentle"
        }
      },
      {
        "value": "sway-vivid",
        "label": {
          "zh": "大摆",
          "en": "Vivid"
        }
      }
    ],
    "label": {
      "zh": "摆动方式",
      "en": "Sway style"
    },
    "hint": {
      "zh": "运行指示器中鲸尾摆动的素材与幅度。",
      "en": "The artwork and amplitude the whale tail swings with in the running indicator."
    }
  },
  {
    "id": "enabled",
    "group": "sway",
    "control": "switch",
    "type": "boolean",
    "default": true,
    "label": {
      "zh": "启用动画",
      "en": "Animate the indicator"
    },
    "hint": {
      "zh": "关闭后运行指示器保持出厂画面。",
      "en": "Turning this off leaves the shipped running indicator untouched."
    }
  },
  {
    "id": "minPeriodMs",
    "group": "speed",
    "control": "number",
    "type": "number",
    "default": 190,
    "min": 60,
    "max": 5000,
    "step": 10,
    "label": {
      "zh": "最快周期（毫秒）",
      "en": "Fastest cycle (ms)"
    },
    "hint": {
      "zh": "峰值速率下整轮摆动的时长。",
      "en": "Full sway duration at the peak token rate."
    }
  },
  {
    "id": "maxPeriodMs",
    "group": "speed",
    "control": "number",
    "type": "number",
    "default": 1500,
    "min": 120,
    "max": 10000,
    "step": 10,
    "label": {
      "zh": "最慢周期（毫秒）",
      "en": "Slowest cycle (ms)"
    },
    "hint": {
      "zh": "空闲或等待工具调用时整轮摆动的时长。",
      "en": "Full sway duration while idle or waiting on a tool call."
    }
  },
  {
    "id": "rateRef",
    "group": "speed",
    "control": "number",
    "type": "number",
    "default": 9,
    "min": 1,
    "max": 400,
    "step": 1,
    "label": {
      "zh": "参考速率（tok/s）",
      "en": "Reference rate (tok/s)"
    },
    "hint": {
      "zh": "速率达到该值时，整轮摆动时长减半。",
      "en": "Token rate at which the full sway cycle halves."
    }
  },
  {
    "id": "maxRate",
    "group": "sampling",
    "control": "number",
    "type": "number",
    "default": 160,
    "min": 1,
    "max": 100000,
    "step": 1,
    "label": {
      "zh": "速率上限（tok/s）",
      "en": "Rate ceiling (tok/s)"
    },
    "hint": {
      "zh": "估算速率的上限，使一次批量重排无法把摆动拉到极端。",
      "en": "Upper bound on the estimated rate, so one bulk re-render cannot peg the sway."
    }
  },
  {
    "id": "charsPerToken",
    "group": "sampling",
    "control": "number",
    "type": "number",
    "default": 1.7,
    "min": 0.1,
    "max": 20,
    "step": 0.1,
    "label": {
      "zh": "每 token 字符数",
      "en": "Characters per token"
    },
    "hint": {
      "zh": "由已渲染文本增量估算 token 速率时的换算系数。",
      "en": "Divisor used to read a token rate from the text the indicator streams."
    }
  },
  {
    "id": "sampleMs",
    "group": "sampling",
    "control": "number",
    "type": "number",
    "default": 200,
    "min": 20,
    "max": 5000,
    "step": 10,
    "label": {
      "zh": "取样间隔（毫秒）",
      "en": "Sampling interval (ms)"
    },
    "hint": {
      "zh": "两次文本长度观测之间的间隔。",
      "en": "Interval between two text-length observations."
    }
  },
  {
    "id": "smooth",
    "group": "sampling",
    "control": "number",
    "type": "number",
    "default": 0.4,
    "min": 0.05,
    "max": 1,
    "step": 0.05,
    "label": {
      "zh": "平滑系数",
      "en": "Smoothing weight"
    },
    "hint": {
      "zh": "每次新观测折算进当前速率的权重，取值 0 到 1。",
      "en": "Weight each fresh measurement carries in the current rate, from 0 to 1."
    }
  }
];
/* dsh-whale-sway:settings:end */

// ---------------------------------------------------------------------
// Schema resolution
// ---------------------------------------------------------------------

/**
 * The paths a `require` is built from, in resolution order.
 *
 * The running profile comes first: DSH keeps the packages its composition can
 * see reachable from there, and the profile directory is exported to the
 * process as `DSH_PROFILE_DIR`. The bundled application root and the process
 * working directory follow, then this module's own directory — which is the one
 * that answers for a package installed normally, with its dependencies beside
 * it. Every candidate is cheap to try and a failure is silent here.
 *
 * @returns absolute paths, de-duplicated, in the order they are tried.
 */
function resolutionBases() {
  const bases = [];
  const push = (value) => {
    if (typeof value !== 'string' || value.length === 0) return;
    if (!bases.includes(value)) bases.push(value);
  };
  push(process.env.DSH_PROFILE_DIR);
  if (typeof process.env.DSH_HOME === 'string' && process.env.DSH_HOME.length > 0) {
    push(join(process.env.DSH_HOME, 'profiles'));
  }
  // The desktop host is launched as
  // `<app root>/dsh/node_modules/@deepseek-ai/dsh-desktop-host/lib/index.js <dsh root> <profile> …`,
  // so an argv entry that names the bundled application root is usable as a
  // resolution base even though the module itself lives outside it.
  const argv = Array.isArray(process.argv) ? process.argv : [];
  for (const entry of argv) {
    if (typeof entry !== 'string') continue;
    if (/[\\/]dsh[\\/]?$/.test(entry) || /app\.asar/.test(entry)) push(entry);
  }
  try {
    push(dirname(fileURLToPath(import.meta.url)));
  } catch (error) {
    /* an opaque module URL: the remaining bases still apply */
  }
  push(process.cwd());
  return bases;
}

/** Build a `require` rooted at one candidate: the entry itself when it is a file, else its directory. */
function requireFrom(entry) {
  const isFile = /\.(?:[cm]?js|json)$/i.test(entry);
  return createRequire(isFile ? entry : join(entry, 'package.json'));
}

/**
 * Resolve the schema factory, or `undefined` when no candidate carries it.
 *
 * @returns the schemastery factory — callable, with `.object()` — or undefined.
 */
function loadSchemaFactory() {
  for (const base of resolutionBases()) {
    let loaded;
    try {
      loaded = requireFrom(base)(SCHEMA_PACKAGE);
    } catch (error) {
      continue;
    }
    const factory = loaded !== null && typeof loaded === 'object' && loaded.default ? loaded.default : loaded;
    if (typeof factory === 'function' || (factory !== null && typeof factory === 'object' && typeof factory.object === 'function')) {
      return factory;
    }
  }
  return undefined;
}

/**
 * Build the Config schema from the generated field table.
 *
 * Each field becomes one schema node with its declared type, bounds, and
 * default, marked `.volatile()` so DSH can apply an edit to the live instance
 * without a remount — and so `volatileForm()` selects it for the settings page.
 *
 * @param factory - the schemastery factory.
 * @param fields - the generated field table.
 * @returns the object schema the Loader validates this row's config against.
 */
function buildConfigSchema(factory, fields) {
  const shape = {};
  for (const field of fields) {
    let node;
    if (field.type === 'enum') {
      node = factory.union([...field.values]);
    } else if (field.type === 'boolean') {
      node = factory.boolean();
    } else {
      node = factory.number();
      if (Number.isFinite(field.min)) node = node.min(field.min);
      if (Number.isFinite(field.max)) node = node.max(field.max);
      if (Number.isFinite(field.step)) node = node.step(field.step);
    }
    shape[field.id] = node.default(field.default).volatile();
  }
  return factory.object(shape);
}

const schemaFactory = loadSchemaFactory();

/**
 * The Loader entry's Config schema — the source of every parameter the settings
 * page exposes. It stays `undefined` (and DSH then serves no form for this
 * entry) when the schema package cannot be resolved, which is the documented
 * degradation rather than a load failure.
 */
const Config = schemaFactory === undefined ? undefined : buildConfigSchema(schemaFactory, SETTINGS_FIELDS);

/**
 * Nothing to set up and nothing to tear down.
 *
 * The one thing worth saying out loud is the degraded case: a composition whose
 * module resolution cannot reach `@deepseek-ai/schemastery` runs the plugin
 * without a settings page, and the reason should be visible in the log rather
 * than a silently missing UI.
 *
 * @param ctx - the Host plugin context.
 */
export function apply(ctx) {
  if (Config !== undefined) return;
  try {
    if (ctx !== null && ctx !== undefined && ctx.logger !== undefined && typeof ctx.logger.warn === 'function') {
      ctx.logger.warn(
        'no %s resolvable from the profile, so this plugin exposes no configurable fields; ' +
          'the animation is unaffected',
        SCHEMA_PACKAGE,
      );
    }
  } catch (error) {
    /* a context without a logger: the plugin still runs */
  }
}

export { Config };
