/**
 * Splice the generated sprite sheet into `client.js`.
 *
 * The sheet is a build artifact — `tools/build-frames.mjs` turns the source
 * artwork into `preview/frames-sheet.png` plus `tools/generated/frames.json`.
 * The runtime needs those bytes *inline*, because a DSH client half is a single
 * classic script: it has no `import` and must not depend on a sibling fetch.
 *
 * This tool is the only writer of the region between the two markers in
 * `client.js`, and it is idempotent: running it twice leaves the same bytes.
 *
 *   node tools/sync-sheet.mjs          # splice (writes client.js when stale)
 *   node tools/sync-sheet.mjs --check  # exit 1 when client.js is out of date
 */

import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BEGIN = '/* dsh-whale-sway:sheet:begin */';
const END = '/* dsh-whale-sway:sheet:end */';
const META_PATH = resolve(ROOT, 'tools/generated/frames.json');
const CLIENT_PATH = resolve(ROOT, 'client.js');

const check = process.argv.includes('--check');
const sha256 = (buffer) => createHash('sha256').update(buffer).digest('hex');

function fail(message) {
  console.error('[sync-sheet] ' + message);
  process.exit(1);
}

if (!existsSync(META_PATH)) {
  fail('missing ' + META_PATH + ' — run `node tools/build-frames.mjs` first');
}

let meta;
try {
  meta = JSON.parse(readFileSync(META_PATH, 'utf8'));
} catch (error) {
  fail('unreadable frames.json: ' + error.message);
}

const count = Number(meta.count);
const cell = Number(meta.cell);
const base64 = typeof meta.pngBase64 === 'string' ? meta.pngBase64 : '';

if (!Number.isInteger(count) || count < 2) {
  fail('frames.json count must be an integer >= 2 (got ' + JSON.stringify(meta.count) + ')');
}
if (!Number.isInteger(cell) || cell < 2) {
  fail('frames.json cell must be an integer >= 2 (got ' + JSON.stringify(meta.cell) + ')');
}
if (base64.length === 0) fail('frames.json pngBase64 is empty');
if (!/^[A-Za-z0-9+/]+={0,2}$/.test(base64)) fail('frames.json pngBase64 is not standard base64');

const bytes = Buffer.from(base64, 'base64');
if (bytes.length < 24 || bytes.toString('latin1', 1, 4) !== 'PNG') {
  fail('pngBase64 does not decode to a PNG');
}
const width = bytes.readUInt32BE(16);
const height = bytes.readUInt32BE(20);
if (width !== cell || height !== count * cell) {
  fail(
    'sheet geometry disagrees with frames.json: PNG is ' +
      width +
      'x' +
      height +
      ', expected ' +
      cell +
      'x' +
      count * cell,
  );
}
const digest = sha256(bytes);
if (meta.sheetSha256 && meta.sheetSha256 !== digest) {
  fail('pngBase64 does not match sheetSha256 in frames.json');
}

const sheetPath = resolve(ROOT, typeof meta.sheet === 'string' ? meta.sheet : 'preview/frames-sheet.png');
if (existsSync(sheetPath)) {
  const onDisk = readFileSync(sheetPath);
  if (sha256(onDisk) !== digest) {
    fail('preview/frames-sheet.png does not match pngBase64 in frames.json — regenerate the sheet');
  }
}

// Keep the indentation that already preceded the opening marker: the slice
// starts *at* the marker text, so the block below must not repeat that indent
// on its first line, and must not end with a newline (the file supplies it).
const block = [
  BEGIN,
  '  // Generated by `node tools/sync-sheet.mjs` from tools/generated/frames.json.',
  '  // Do not edit by hand: `node tools/build-frames.mjs` regenerates the sheet',
  '  // from the source artwork and the sync tool fills these four values in.',
  "  var FRAME_SHEET_BASE64 = '" + base64 + "';",
  '  var FRAME_COUNT = ' + count + ';',
  '  var FRAME_CELL = ' + cell + ';',
  '  var FRAME_SOURCE = ' + JSON.stringify(String(meta.source || '')) + ';',
  '  ' + END,
].join('\n');

const source = readFileSync(CLIENT_PATH, 'utf8');
const begin = source.indexOf(BEGIN);
const end = source.indexOf(END);
if (begin < 0 || end < 0 || end < begin) {
  fail('client.js is missing the sheet markers');
}
if (source.indexOf(BEGIN, begin + 1) >= 0 || source.indexOf(END, end + 1) >= 0) {
  fail('client.js has duplicate sheet markers');
}

const next = source.slice(0, begin) + block + source.slice(end + END.length);

if (next === source) {
  console.log('[sync-sheet] client.js is already in sync');
} else if (check) {
  fail('client.js is out of date — run `node tools/sync-sheet.mjs`');
} else {
  writeFileSync(CLIENT_PATH, next);
  console.log('[sync-sheet] spliced the sheet into client.js');
}

console.log(
  '[sync-sheet] frames=' +
    count +
    ' cell=' +
    cell +
    ' png=' +
    bytes.length +
    'B base64=' +
    base64.length +
    ' chars sha256=' +
    digest.slice(0, 16) +
    ' source=' +
    String(meta.source || '(unset)'),
);
